### ISSUE TITLE
OpenSSL decrypt warning in logs

### ISSUE THREAD

**Issue by kolynet** [abantecart/abantecart-src#1015]
I randomly get this, i didnt figure out the exact reason when its happening, will try to investigate, but i think it will be a bug related to some storefront action.

2017-10-27 1:56:18 - warning: AbanteCart core v.1.2.11 openssl_decrypt(): Failed to base64 decode the input in <b>/home/public_html/core/lib/encryption.php</b> on line <b>81</b>

**Comment by abantecart** [comment]
This can be due to primarily 2 things. 

1. You can have data somewhere in the database that was not saved completely. Because of that base64 can not decode that string. 

2. Someone can mess with your site by passing URLs that have incorrect base64 string in params. 

Both of the above cases will not lead to the bug in AbanteCart.

Please monitor and if this turns to be a bug, reopen this ticket.
