### ISSUE TITLE
weight modifier in the options issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1501]
Cart incorrectly calculates the total weight of the product. The base product weight was ignored.
Note: the name of the field is Weight Change: Enter the difference between the base product and the option product

<img width="1685" alt="weightopt" src="https://user-images.githubusercontent.com/2631910/134302917-0fb65bc7-8c29-49fc-8e58-272006013d65.png">

**Comment by BasaraABC** [comment]
Discussed: we need to change the field description

**Comment by abolabo** [comment]
Please give a text

**Comment by abantecart** [comment]
Description for weight option:
Important! If value provided as %(percent) option weight will be changed by specified percent based on the main product weight. If weight value provided it will be used as absolute value for the option, main weight will be ignored.

**Comment by goatlady102** [comment]
I am concerned after reading this text change.  

If I am reading your text change correctly as seen here:
Description for weight option:
Important! If value provided as %(percent) option weight will be changed by specified percent based on the main product weight. If weight value provided it will be used as absolute value for the option, main weight will be ignored.

I would like to bring to your attention this a reversal of how options in AbanteCart Versions 1.3.1 and earlier handle option wt.  If you change the additional wt to what your text indicates as an absolute value in the option -  that will require ALL existing carts that use options and have weight input to be re-done.  I suspect Admins will not be pleased with this additional work.  

And I failed to understand the connection of a product shipping wt as a percentage of a base product.  Just because a bottle may contain twice as much product-  does not mean the actual wt of the larger bottle is double the base product wt -  are the containers the same material,  etc.  

Please rethink what appears to be a chaos waiting to happen or enlighten my wrong conclusion of your intent

**Comment by abantecart** [comment]
Thank you @goatlady102 for bringing this up. I was under impression that we do not change the way the options weight is currently working. We were just trying to clarify it. @abolabo @BasaraABC Please correct me if I missed something. 
We will have one more discussion internally. 
Meanwhile, @goatlady102, can you please provide some existing use case (if you have any) with option weight absolute and % based modifier

**Comment by goatlady102** [comment]
Well guys,  this was enlightening!! And slightly confusing but here re my findings.

In AbanteCart docs:
https://abantecart.atlassian.net/wiki/spaces/AD/pages/9568257/Manage+Products+Options
The title of the wt field in the options is Weight Change (the field name prior to v 1.3.1 was Weight)
In the text description it is :
Weight: Enter the weight difference between the base product and the selected option value

In making an example for you we have found that v1.3.1 had the change to the field title.  In running the examples, we find that the shopping cart wt has always used the actual wt in the options.  It is unknown what admins placed in the field previously.  
It seems you,  core devs, just need to decide what you want to do with that field -  title it appropriately and define the contents.

Reverting back to just weight,  not Weight Change,  and leaving the cart calculations as they are now seems the best solution.
That will all the cart wt functions and shippers rate look up for both default our our WHY2 shipper extensions working as they always have.

So Pavel,  you are correct -  you were adding clarity to the field - so just remove the "change" and update the documention to match the new tool tip  and I believe all will be good.

![options wt](https://user-images.githubusercontent.com/7943102/135566967-844d39e5-d2bc-4c0b-96d6-c337f4d07989.png)
