### ISSUE TITLE
Issue in coupon listing grid not showing the correct on/off status

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#1539]
Hi admins,

We found out that in AbanteCart v1.3.2, the coupon listing grid is not showing the correct on/off status like in the edit page status.

This is what the listing grid shows:
![image](https://user-images.githubusercontent.com/225439/177614878-d9062fd8-8640-4914-9fdd-0c894bb3fd40.png)

While in the edit coupon page:
![image](https://user-images.githubusercontent.com/225439/177614910-7c34cc7c-b1a5-46eb-acb0-183031958618.png)

I checked the core code and found out that in the model. The coupon status is based on `$sqlDateRange = "(CASE WHEN c.date_start < NOW() AND c.date_end > NOW() THEN 1 ELSE 0 END)";`, not the actual coupon status.

Is this intentionally changed or is it a bug?

**Comment by BasaraABC** [comment]
Did you change coupon status in the grid? If yes, please reload page

**Comment by handoyo** [comment]
yes i did. coupon status is the listing grid are not changed.

**Comment by BasaraABC** [comment]
Please post all coupon settings and step-by-step what did you do.

**Comment by handoyo** [comment]
I create a new coupon: 
Status: Off
Coupon Name: Test
Coupon Description: Testing
Code: test
Type: Percentage
Discount: 10.00
Date Start: 07/06/2022
Date End: 07/09/2022
Uses Per Coupon: -
Uses Per Customer: -

When i open the coupon listing grid, the coupon status is turned ON, but in the edit page the status is OFF

**Comment by goatlady102** [comment]
Hi Basara - Lee here - let me add clarity here-  this action is the same in all the 1.3.2 installations we have.  
in 1.3.2 cart versions it seems the coupon grid keys off the coupon date for reporting the on/off condition.  
If the edit page is set to off,  the coupon does not work in the cart which is correct action.  But in order to get the grid to report correctly  one has to change the edit page stop date to at least one day earlier than the current date -  then grid will show off setting,  the same as edit setting.   That is new behavior in cart 1.3.2   We are running PHP 8.0 in all our installations.

Unless the expiring date is manual changed.  it does not matter how many times we set the grid to off.  It will show off UNTIL we leave the grid page and come back to it, or refresh the page -  it will have reverted to the ON condition,  even with the edit page still off.

**Comment by BasaraABC** [comment]
@abolabo to replicate create the coupon with params described by handoyo, next set status to OFF and click save button (at the very bottom of page). then go to the listing grid. The status showed as ON.
I think we should separate status from the date range.

**Comment by handoyo** [comment]
Hi @BasaraABC and @abolabo ,

I tested again on 1.3.3 and found out that the issue still occurs. I tried to turn ON via the listing grid, saved the status and when i refresh, the status is still OFF.

A fix would be appreciated.

Thanks.

**Comment by abolabo** [comment]
@handoyo . please check activation date range  of coupon. It's not a bug.

**Comment by BasaraABC** [comment]
> I think we should separate status from the date range.

**Comment by abolabo** [comment]
@BasaraABC how it can be an active within non-current date range? i think all works fine there

**Comment by BasaraABC** [comment]
Please read the description again. The case of the bug: listing shows ON but coupon details show OFF. Should be consistent (whatever approach you choose status should show the same in the listing and details page).

**Comment by BasaraABC** [comment]
The issue is not fixed.
<img width="1404" alt="status" src="https://github.com/abantecart/abantecart-src/assets/2631910/5c1e4238-4a8e-49b9-903f-f75aa79087e6">

https://github.com/abantecart/abantecart-src/assets/2631910/45a3fb6c-143d-486d-810c-ba0b1e085966
