### ISSUE TITLE
+ sign in the product details cannot be saved

### ISSUE THREAD

**Issue by ghost** [abantecart/abantecart-src#1547]
there is a new issue regarding to some new codes 1.3.3 on php8.1 
if you save any field with the + sign, it will just be replaced with space

**Comment by kolynet** [comment]
upgraded db and all tables to innodb+ utf8mb4 unicode ci i also tried general ci but i think its not sql issue. mysql8.

**Comment by abolabo** [comment]
Please try current dev v1.3.4. We already fixed this bug in it.

**Comment by BasaraABC** [comment]
@abolabo current 1.3.4 branch has this behavior. I remember we change this in 1.3.3 due to some security concerns. Please fix this if you can.

**Comment by kolynet** [comment]
could be encoding decoding in admin model catalog product, or maybe storing encoded variant like %2B for example. if i change in database it works, but once i update any product details on admin it will remove characters everywhere

how can i download or access 1.3.4 files? couldnt find it

**Comment by abolabo** [comment]
we already investigated this this issue. Don't know how to solve it because + can be used inside http url as concatenation of strings. For example http://www.domain.com?product_description=some+product. 
On php side parameter becomes $_GET['product_description'] = "some product"; 
+ replaced with whitespace by web-server, not php. 
To solve this issue needs to think about preparing of data before sending for all forms. 
I have no solution yet. Still thinking.

**Comment by kolynet** [comment]
i think one solution would be function urlencoding which converts to %20 %2B and decode on form loading, probably some escape function has conflict with new php
