### ISSUE TITLE
Critical Error Logging In To AbanteCart

### ISSUE THREAD

**Issue by HolgateUK** [abantecart/abantecart-src#1690]
I have been using AbanteCart for a good while with no issues, but this morning while trying to log in I went to a screen with this message:

There has been a critical error processing your request
SQL Error: Incorrect TIMESTAMP value: '1715081783'
Error No: 1525
SQL: SELECT * FROM abss_currencies WHERE code != 'GBP' AND date_modified > '1715081783' in /home/customer/www/holgatecoins.com/public_html/core/database/amysqli.php on line 114

I have tried logging in from my laptop and my smartphone with the same result.

Thanks in anticipation of any help sorting this out.

**Comment by pavelrojkovtrepp** [comment]
Something happened with your host or PHP that it does not set a correct date.  Value '1715081783' is not a valid date. 
What version of PHP do you use?

**Comment by abolabo** [comment]
hi,
what version php do you use?
i see in the code this[ query](https://github.com/abantecart/abantecart-src/blob/master/public_html/admin/model/localisation/currency.php#L222)
As you see there is no timestamp, it should be a datetime format.
Can you debug this place?

**Comment by HolgateUK** [comment]
Thanks for your reply pavelrojkovtrepp and abolabo.
I am using PHP 7.4.33

**Comment by HolgateUK** [comment]
I have read from a post on the AC forum that it may be solved by updating my version of AC.
https://forum.abantecart.com/index.php/topic,9454.msg37300.html#msg37300
Any thoughts on this?

**Comment by abolabo** [comment]
> @abolabo > hi, what version php do you use? i see in the code this[ query](https://github.com/abantecart/abantecart-src/blob/master/public_html/admin/model/localisation/currency.php#L222) As you see there is no timestamp, it should be a datetime format. Can you debug this place? How would i go about debugging? I am not a professional developer or anything.

you can try replace file public_html/admin/model/localisation/currency.php
with this https://github.com/abantecart/abantecart-src/blob/master/public_html/admin/model/localisation/currency.php (click download button) 
If does not help try to upgrade your AbanteCart.

**Comment by HolgateUK** [comment]
Thanks @abolabo. That didn't work so I am upgrading AC from 1.2.15 to 1.2.16.
I have copied the code directory over and run the modified.upgrade.sql file in phpMyAdmin.

I am confused about what to do with the upgrade.php file. Do i just manually copy the code into /folder_where_cart_installed/admin/controller/common/head.php? The instruction is to copy it in "about line 30". 
I assume that folder_where_cart_installed is public_html in my case?

"About line 30" is a bit vague. Is there a specific line that it should go in at?

Also not sure what it means when it says i should "include('/yourpathtofile/upgrade.php')"

**Comment by BasaraABC** [comment]
It seems like the issue might be due to the older version 1.2.15, which is known to have compatibility problems with newer PHP versions. This could be particularly relevant if your hosting service has recently upgraded their PHP or related modules. Contact hosting and ask what they changed.

I recommend moving this discussion to the [AbanteCart community forum](https://forum.abantecart.com/) where it's more suited for version-specific advice. The bug tracker here is primarily for issues concerning the latest version, which is currently 1.3.4.

For your current upgrade process, you might want to follow the manual upgrade guide to ensure that everything is set up correctly. Here's the guide for manual upgrades https://abantecart.atlassian.net/wiki/spaces/AD/pages/4980799/AbanteCart+Upgrade
