### ISSUE TITLE
New instalation AbantaCart but admin password incorrect (while it is correct)

### ISSUE THREAD

**Issue by Maartensworld** [abantecart/abantecart-src#1695]
I just had a new installation of AbantaCart on my website and when I want to login as admin, the username or password is incorrect.
Now, I know for a fact it is correct. I filled it in myself and took a screenshot of it, so No, I am not mistaken.

But it gets better... or worse:  When I then try to recover the password by clicking the link "forgot password", I receive an email with a link to click... but the link is invalid. (again, tried it 4 times)

So, what do I do?

**Comment by Maartensworld** [comment]
Hi.
It was installed by my hosting provider (Namecheap).

The version is 1.3.4

I did not set up a database, but I am sure the auto installer did this.

For the rest I know very little as all I can see is the login page.

Regards
Maarten

**Comment by BasaraABC** [comment]
It appears there might be an issue with the auto-installer, which is not controlled by AbanteCart. I recommend removing the current installation and attempting the process again. Since this does not seem to be a bug report, please consider creating a topic in the AbanteCart community forum: https://forum.abantecart.com/

Here is the guide to the standard AbanteCart installation https://abantecart.atlassian.net/wiki/spaces/AD/pages/4391051/Regular+Installation
