### ISSUE TITLE
no way to close completed wizard

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#240]
1. after complete click CLOSE button
2. visit Dashboard page again

<b>Bug: popup appear again</b> see screen (tested in Chrome)
<img width="1055" alt="2015-08-31_15-07-21" src="https://cloud.githubusercontent.com/assets/2631910/9574586/5afc75b4-4ff2-11e5-97fb-c0321e3bd8d9.png">

**Comment by abantecart** [comment]
Modal will not show if completed. If opened again and click back it will show again. This is ok as once logo our or session lost there we be no modal ever on main page

Note: back step is implemented. There is no saving on back step clicking!!!!!!!!!!!!!!
There is no warning on click, so all changes will be lost. This is intentional.
