### ISSUE TITLE
admin/system pesmissions pre-validation check

### ISSUE THREAD

**Issue by abolabo** [abantecart/abantecart-src#278]
need to add check for permissions for folder admin/system and recreate subfolders with 777 (backup, temp etc)

**Comment by abolabo** [comment]
fixed

**Comment by abolabo** [comment]
fixed

**Comment by abantecart** [comment]
I think we are done here. Boris, see if you notice anything.

**Comment by BasaraABC** [comment]
In my opinion we need to make messages more clear or add help links.
* *Incorrect PHP memory limit. Some Abantecart functions will not work with memory limit less than 128Mb* 
Almost all user dont know how to change limit
* *...config.php file needs to be set to read and execute modes to keep it secured from editing!*
A lot of forum user ask for help because dont know how easy change this via FTP or Cpanel filemanager

**Comment by abantecart** [comment]
Fixed.
