### ISSUE TITLE
product SEO url and category key issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#659]
original post http://forum.abantecart.com/index.php/topic,4887.msg21132.html#msg21132
Issue: cart should return _page not found_ if category key is not exist like site.com/**category_seo_key**/product_seo_key

**Comment by goatlady102** [comment]
Hi guys,  you need to check this situation on normal default code.   He runs one of his extensions called Force Category and he did cause some issues previously.  Just FYI.

**Comment by abolabo** [comment]
tried on 1.2.9. When i marks 2 different categories with seo keys and compounds them into url 
for ex. http://www.domain.com/first_seo/second_seo it works anyway.
When category with first_seo disabled - opens second.
Otherwise always opens first_seo.
When both seo_keys are valid - always opens first.
i don't see problem

**Comment by BasaraABC** [comment]
@goatlady102 thank you for feedback
@abolabo thanks but issue not with 2 categories but with deleted/disabled category and **product**.

**Comment by abantecart** [comment]
I do not think this is a problem. If you explicitly specified category in SEO and that category is disabled, second SEO key (product) should not matter.  This will display "not found".
