### ISSUE TITLE
Guest Checkout: Incomplete order remains forever in DB

### ISSUE THREAD

**Issue by hb007006** [abantecart/abantecart-src#761]
Storefront:

1. Add products into cart.
2. Checkout cart as a Guest
3. Fill all details in Guest Checkout Step -1 
4. Navigate till Checkout Confirmation page
5. Do not confirm order and close browser

![1](https://cloud.githubusercontent.com/assets/22338790/21293205/56b4a586-c543-11e6-8b5d-169a2ece2fd7.png)
![2](https://cloud.githubusercontent.com/assets/22338790/21293206/588b9a90-c543-11e6-8bf2-de322db7f694.png)
![3](https://cloud.githubusercontent.com/assets/22338790/21293207/5bc23a34-c543-11e6-841d-45cfbc6f0fbd.png)
![4](https://cloud.githubusercontent.com/assets/22338790/21293208/5eed7016-c543-11e6-9612-1aaa24d264d6.png)

**6. Again open browser. Cart will be empty however DB will have incomplete order**

![5](https://cloud.githubusercontent.com/assets/22338790/21293210/6e5a7ddc-c543-11e6-9566-1f1d7038e9d4.png)

**Comment by abolabo** [comment]
it depends on cookie expiration time. AbanteCart  use zero, that means cookie will alive while browser is open. If you want to change it you should set some time in ASession library, but in that case cookie will expire by time and this process will depends on browser activity. i think it's not a problem when you have some periodical ajax-request to some controller.
But I'm not sure that we should to change something in code now.

**Comment by abantecart** [comment]
I wonder why this is reported as an issue. This is exactly how process is intended to work. If checkout is attempted there will be incomplete order. 

Can you please explain on the the issue. If this is a suggestion to improvement, please take it to our forum for discussion. 

This section is for reporting bugs and issues only

**Comment by hb007006** [comment]
No, this is not a suggestion. It is a defect. This is not related to customer. Functionality is working fine for customers.
This issue is specifically for guest users.

1. Add products into cart
2. Checkout cart as a Guest
3. Fill all details in Guest Checkout Step -1
4. Navigate till Checkout Confirmation page
5. Do not confirm order and close browser
6. Again open browser. Cart will be empty however DB will have incomplete order

Even it wont resolve with cookie expiration time. Lets take an example, you set cookie expiration time as 1 day. Guest added some products to his/her cart, navigate till Checkout Confirmation page and do not confirm order and close browser. Next day after 24 hours, if opens browser again. Cart will be empty however DB will have incomplete order.

**Comment by goatlady102** [comment]
This is a correct action to have happen to keep the integrity of the numbering (order id) in the database to be intact without missing sequence.   I believe the system assigns an order number with the first add to cart item.   That order number is sequential.   The next customer is assigned the next number and so on.  That order number is then "used" in regards to the database and makes complete sense in the auditing side of a business.   When a store owner or an accountant looks at print outs of transactions -  missing numbers in a numbering sequence need to be accounted for  -  otherwise there is a reasonable expectation of potential  mismanagement.  And to re-assign an  unused order number after some time frame is an incorrect solution

abantecart is correct in that how is works is exactly how it is intended to work  and it is also exactly how any good accountant or auditor will say it should work.

**Comment by BasaraABC** [comment]
Thanks everyone for comments and opinions. To continue discussion please create new topic in the forum.
