### ISSUE TITLE
contact us: sender email improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#788]
Improve required for email enquiry from contact us form.  **From** email is confusing users because it is site owner email. 
http://forum.abantecart.com/index.php/topic,5441.msg23436.html#msg23436
![2017-02-22_15-52-27](https://cloud.githubusercontent.com/assets/2631910/23204177/11933234-f918-11e6-873a-0bcaa0322509.png)

**Comment by BasaraABC** [comment]
Please read this post http://forum.abantecart.com/index.php?topic=5441.msg23443#msg23443
It is important

**Comment by abantecart** [comment]
To avoid a risk of loosing email notification, I propose to store contact details into message. This way inquiries, will not be lost in transmission. 

Duplicate inquiry comments + email + names into message. 
Add setting in details section:
"Duplicate contact inquiries to messages" (On by default) <help> Reduce a risk of loosing customer inquiries due to email or transmission issues.
