### ISSUE TITLE
create menu: LINK button improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#802]
For users not clear that to assign category or content page need to click Link button.
Please rename it to something more clear like _Click to Link_
and please change button title it is incorrect.
<img width="623" alt="2017-03-16_12-50-45" src="https://cloud.githubusercontent.com/assets/2631910/23983538/3999f8f4-0a47-11e7-9c30-d67272232e84.png">

**Comment by onyxnz** [comment]
Suggestion:
How about doing away with it altogether, and just utilising jQuery already there to load the URL?
eg Menu_form.tpl line 91:
$('#link_page').click(function(){
        var c_id = $('#menu_information').val();
change to
$('#menu_information').click(function(){
        var c_id = $('#menu_information').val();
This works, albeit requiring a click, hold, choose from drop-down, rather than choose, then click another button.
I am unsure about the touch-screen devices with this code, though; haven't any way to test that right now.

**Comment by abolabo** [comment]
i think more clear now

**Comment by abantecart** [comment]
UI is still no very clear. 
I think we need to have selector for link type and based on the selection, we show category, page or text field to enter value. 
No need for text field if category or page is selected. Text field is needed only for text link. 
This will probably require one more column for menu type. 

We should discuss this more.

**Comment by BasaraABC** [comment]
### Issue A:. When edit menu item -  incorrect link type selected by default. This is confusing
### Issue B: Please make Link type dropdown width larger
<img width="860" alt="2017-03-23_13-16-28" src="https://cloud.githubusercontent.com/assets/2631910/24234895/41b96836-0fcd-11e7-8918-c386ff3d6bcf.png">
