### ISSUE TITLE
product option's values and Stock message

### ISSUE THREAD

**Issue by afrianviolet** [abantecart/abantecart-src#851]
I disable "Display Stock" in backend->setting->general.
Then add an option in product with a few options with quantity and some with 0 quantity. The options with 0 quantity will show "In stock" in frontstore product page.
Please fix it.  (abantecart v1.2.10)
Thank you!

**Comment by BasaraABC** [comment]
Hello @afrianviolet. In your product setting please check _Out Of Stock Status_ setting value. Change it to 'out of stock' so correct status will be shown near product option 
see 
<img width="544" alt="2017-05-01_14-10-02" src="https://cloud.githubusercontent.com/assets/2631910/25574361/ed95ac5a-2e77-11e7-9034-011f26dfe707.png">


<hr>
But improvement in this area required, as reported by @afrianviolet if set 'Display stock' to Off, the option value with negative or 0 quantity show 'out of stock' status. Now 'Display stock' work  differently for main product quantity and product option's quantity.
For example if we have 'Display stock' ON, main product quantity 1000, option value 10 quantity so in result we have for main quantity "Availability 1000"  but for product option value "In stock" message


if we have 'Display stock'  OFF, **main product quantity** 1000, option value 10 quantity so in result we have for main quantity "Availability Instock"  but for **product option value** no message at all if q-ty >0 and 'Out of stock' if q-ty 0


It is confuse users because for main product q-ty setting work like "Display stock q-ty" but on option's level work like "Display stock status" for option value with q-ty > 0 and do not work for option's value with q-ty 0

![stock2](https://cloud.githubusercontent.com/assets/2631910/25574290/34bbcb56-2e77-11e7-8c74-9aa327abd170.png)

**Comment by afrianviolet** [comment]
OK! Get it. It seems that the out of stock status is not controlled by the setting->general and it is controlled in the product detail->general. A little bit confusing.

**Comment by abantecart** [comment]
It is confusing, I agree. We will review this soon

**Comment by abolabo** [comment]
![212121212](https://user-images.githubusercontent.com/1264239/29936348-9311e05a-8e8a-11e7-97b2-5f442d52a210.png)

**Comment by BasaraABC** [comment]
In my opinion we have more confuse than before fixes.
Option value with Quantity 0 and Track stock enabled shown in storefront as In Stock.
![2017-09-04_18-16-22](https://user-images.githubusercontent.com/2631910/30024373-b0ebdce6-919d-11e7-9255-91a2e6830c09.png)

**Comment by abantecart** [comment]
Needs QA

**Comment by BasaraABC** [comment]
UI issue. If Stock Checkout enabled (quantity and track stock no matter - customer can purchase any ) the out of stock message shown  for the options with q-ty 0 and enabled track stock. 
We need to discuss again both #962 and this issues.
![2017-09-06_15-39-27](https://user-images.githubusercontent.com/2631910/30102864-1c4e8cd0-931b-11e7-9c94-3687754bdafa.png)
