### ISSUE TITLE
improve add transaction text

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#857]
Some user confuse how to add new transaction. Please rename field name and add placeholder to input. See example below
<img width="603" alt="2017-05-05_12-47-05" src="https://cloud.githubusercontent.com/assets/2631910/25734896/666ddf78-3191-11e7-94f7-c0f77b2e7f72.png">

**Comment by fathira** [comment]
add new custom transaction type box missing 
see forum   http://forum.abantecart.com/index.php/topic,5625.0.html

**Comment by fathira** [comment]
hi
why to transaction type box missing  ? see answer
my cloudflare setting included Rocket Loader setting on with automatic mode . it is improve speed to hi level  ( page speed yellow 78  Rocket Loader on to increase green 93 it is impotent for abantecart speed optimization) now Rocket Loader off  custom transaction type box  showing now why this see blow 
What does Rocket Loader do?

Rocket Loader can improve load times for pages that include JavaScript. Your search engine ranking may be improved by reducing page load time.

Rocket Loader improves page load times by:

Decreasing the number of network requests by bundling JavaScript files, even third party resources, to avoid slowing down page rendering
Asynchronously loading scripts, including third party scripts, so that they do not block the content of your page from loading immediately
Caching scripts locally (using LocalStorage, available on most browsers and smart phones) so they aren't refetched unless necessary

What Rocket Loader setting should I use?

Automatic: Optimize all JavaScript resources on your website. No configuration required
Manual: Selectively enable Rocket Loader for individual scripts. Add the following attribute to the script tag for each script where you want to enable Rocket Loader:
data-cfasync="true"

Note: The 'data-cfasync' attribute must be added to the HTML script tag before the 'src' attribute (adding the attribute via JavaScript is not sufficient).

Rocket Loader is considered Beta because it’s an experimental feature that modifies the loading and execution flow of Javascript. While efforts are taken to increase Rocket Loader’s compatibility with third-party Javascripts, not all scripts work with this feature. Issues with Rocket Loader affect only a small percentage of customers. 
how to solve this ? it is impotent of abantecart 
https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-
thanks
fathira
